definitions:
  shared_workflow: &shared_workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

  scripts:
    - &shorebird_install
      name: Install Shorebird
      script: |
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &get_fvm_flutter_version
      name: Get Flutter version from .fvmrc
      script: |
        FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
        if [ -z "$FLUTTER_VERSION" ]; then
          echo "Failed to read Flutter version from .fvmrc"
          exit 1
        fi
        echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $CM_ENV

  publishing:
    slack_notify: &slack_notify
      channel: "$SLACK_CHANNEL"
      notify_on_build_start: false
      notify:
        success: true
        failure: true

workflows:
  android-release:
    <<: *shared_workflow
    name: Android Release
    environment:
      flutter: fvm
      android_signing:
        - android_upload_keystore
      groups:
        - firebase
        - google_play
        - shorebird
      vars:
        PACKAGE_NAME: "com.rururu.lifebt"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - *shorebird_install
      - *get_fvm_flutter_version
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Restore Firebase config
        script: |
          echo "$FIREBASE_OPTIONS_DART_BASE64" | base64 --decode > lib/firebase_options.dart
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/google-services.json
      - name: Prepare Android release notes
        script: |
          file="release_notes.json"
          tmp="$(mktemp)"
          jq 'map(if .language == "ja" then .language = "ja-JP" else . end)' "$file" > "$tmp"
          mv "$tmp" "$file"
      - name: Shorebird Release Android
        script: |
          GOOGLE_PLAY_TRACK="${GOOGLE_PLAY_TRACK:-internal}"
          BUILD_NAME=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
          BUILD_NUMBER=$(($PROJECT_BUILD_NUMBER + 50))
          shorebird release android \
            --flutter-version="$FLUTTER_VERSION" \
            --build-name="$BUILD_NAME" \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
      slack: *slack_notify

  ios-release:
    <<: *shared_workflow
    name: iOS Release
    integrations:
      app_store_connect: codemagic-ci-cd
    environment:
      flutter: fvm
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rururu.lifebt
      groups:
        - firebase
        - shorebird
      vars:
        APP_STORE_APPLE_ID: 6449723058
    scripts:
      - *shorebird_install
      - *get_fvm_flutter_version
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --custom-export-options={\"manageAppVersionAndBuildNumber\":false}
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install FlutterFire CLI
        script: |
          dart pub global activate flutterfire_cli
      - name: Restore Firebase config
        script: |
          echo "$FIREBASE_OPTIONS_DART_BASE64" | base64 --decode > lib/firebase_options.dart
          echo "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Shorebird Release iOS
        script: |
          BUILD_NAME=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
          BUILD_NUMBER=$(($PROJECT_BUILD_NUMBER + 50))
          shorebird release ios \
            --flutter-version="$FLUTTER_VERSION" \
            --build-name="$BUILD_NAME" \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: $SUBMIT_TO_APP_STORE
        release_type: AFTER_APPROVAL
      slack: *slack_notify
