workflows:
  android-release:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: fvm
      android_signing:
        - android_upload_keystore
      groups:
        - firebase
        - google_play
      vars:
        PACKAGE_NAME: "com.rururu.lifebt"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Restore Firebase config
        script: |
          echo "$FIREBASE_OPTIONS_DART_BASE64" | base64 --decode > lib/firebase_options.dart
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/google-services.json
      - name: Build AAB with Flutter
        script: |
          GOOGLE_PLAY_TRACK="${GOOGLE_PLAY_TRACK:-internal}"
          BUILD_NAME=$(grep '^version:' pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release \
            --build-name="$BUILD_NAME" \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
      slack:
        channel: "$SLACK_CHANNEL"
        notify_on_build_start: false
        notify:
          success: true
          failure: true
