name: life_battery
description: 'A new Flutter project.'
publish_to: 'none'

version: 2.3.0+16

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  in_app_review: ^2.0.10
  intl: ^0.20.2
  introduction_screen: ^3.1.14
  path: ^1.9.1
  riverpod_annotation: ^2.6.1
  sqflite: ^2.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/first_tutorial_ja.gif
    - assets/images/second_tutorial_ja.gif
    - assets/images/third_tutorial_ja.gif
    - assets/images/first_tutorial_en.gif
    - assets/images/second_tutorial_en.gif
    - assets/images/third_tutorial_en.gif
