name: life_battery
description: 'Visualize your life remaining as a battery percentage.'
publish_to: 'none'

version: 2.3.0+16

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  in_app_review: ^2.0.11
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  riverpod_annotation: ^3.0.3
  sqflite: ^2.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/first_tutorial_ja.gif
    - assets/images/second_tutorial_ja.gif
    - assets/images/third_tutorial_ja.gif
    - assets/images/first_tutorial_en.gif
    - assets/images/second_tutorial_en.gif
    - assets/images/third_tutorial_en.gif
