name: Android CD

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter using FVM
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Fetches and resolves project dependencies
        run: flutter pub get

      - name: Create key.jks
        run: echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > release.jks
        working-directory: ./android/app

      - name: Create key.properties
        run: |
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' > key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> key.properties
          echo 'storeFile=release.jks' >> key.properties
        working-directory: ./android/app

      - name: Build app bundle
        run: flutter build appbundle
