name: Android Release

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Google Play track"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic Android release
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: ${{ vars.CODEMAGIC_APP_ID }}
          workflow-id: android-release
          token: ${{ secrets.CODEMAGIC_API_TOKEN }}
        env:
          CM_GOOGLE_PLAY_TRACK: ${{ github.event.inputs.lane }}
