name: Android CD

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter using FVM
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Fetches and resolves project dependencies
        run: flutter pub get

      - name: Create key.jks
        run: echo '${{ secrets.KEYSTORE_BASE64 }}' | base64 -d > android/key.jks

      - name: Verify keystore exists
        run: |
          echo "Listing files in android directory"
          ls -l android/key.jks

      - name: Create key.properties
        run: |
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' > android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
          echo 'storeFile=key.jks' >> android/key.properties

      - name: Verify key.properties exists
        run: |
          echo "Listing files in android directory"
          ls -l android/key.properties

      - name: Build app bundle
        run: flutter build appbundle --verbose
# on:
#   push:
#     branches:
#       - main
#       - name: Run linter
#         run: flutter analyze
#       - name: Run tests
#         run: flutter test
