name: iOS Beta Release

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic iOS beta release
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: ${{ vars.CODEMAGIC_APP_ID }}
          workflow-id: ios-beta-release
          token: ${{ secrets.CODEMAGIC_API_TOKEN }}
        env:
          CM_SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
